exercise_categories = {'🟦': 'Hip_Dominant',
                       '🔵': 'Hip_Dominant',
                       '🟥': 'Knee_Dominant',
                       '🔴': 'Knee_Dominant',
                       '🟩': 'Upper_Push',
                       '🟢': 'Upper_Push',
                       '🟪': 'Upper_Pull',
                       '🟣': 'Upper_Pull',
                       '🟧': 'GPP_Triceps',
                       '🟠': 'GPP_Triceps',
                       '🟨': 'GPP_Biceps',
                       '🟡': 'GPP_Biceps',
                       '⬛️': 'GPP_Calves',
                       '⚫️️': 'GPP_Calves',
                       '🟫': 'GPP_Lateral_Deltoid',
                       '🟤': 'GPP_Lateral_Deltoid',
                       '⬜️': 'GPP',
                       '⚪️️': 'GPP'}

