exercise_categories = {'🟦': 'Hip Dominant',
                       '🔵': 'Hip Dominant',
                       '🟥': 'Knee Dominant',
                       '🔴': 'Knee Dominant',
                       '🟩': 'Upper Push',
                       '🟢': 'Upper Push',
                       '🟪': 'Upper Pull',
                       '🟣': 'Upper Pull',
                       '🟧': 'Triceps',
                       '🟠': 'Triceps',
                       '🟨': 'Biceps',
                       '🟡': 'Biceps',
                       '⬛️': 'Calves',
                       '⚫️️': 'Calves',
                       '🟫': 'Lateral Deltoid',
                       '🟤': 'Lateral Deltoid',
                       '⬜️': 'None',
                       '⚪️️': 'None'}

